-- ============================================================
-- NOVA — TRIGGERS DE AUTOINCREMENTO (patrón clásico SEQUENCE + TRIGGER)
-- Alternativa a GENERATED ALWAYS AS IDENTITY, para Oracle 11g o
-- cuando el curso pide ver el patrón explícito de secuencia + trigger.
-- ============================================================

-- ------------------------------------------------------------
-- PASO 1: quitar la propiedad IDENTITY de cada PK
-- (solo necesario si ya creaste las tablas con el script anterior)
-- ------------------------------------------------------------
ALTER TABLE NOVA_ROL MODIFY ROL_ROL DROP IDENTITY;
ALTER TABLE NOVA_USUARIO MODIFY USU_USUARIO DROP IDENTITY;
ALTER TABLE NOVA_MARCA MODIFY MAR_MARCA DROP IDENTITY;
ALTER TABLE NOVA_CATEGORIA MODIFY CATE_CATEGORIA DROP IDENTITY;
ALTER TABLE NOVA_PRODUCTO MODIFY PRODU_PRODUCTO DROP IDENTITY;
ALTER TABLE NOVA_VARIANTE MODIFY VAR_VARIANTE DROP IDENTITY;
ALTER TABLE NOVA_ALMACEN MODIFY ALM_ALMACEN DROP IDENTITY;
ALTER TABLE NOVA_INVENTARIO MODIFY INV_INVENTARIO DROP IDENTITY;
ALTER TABLE NOVA_MOVIMIENTO_INVENTARIO MODIFY MOVI_MOVIMIENTO DROP IDENTITY;
ALTER TABLE NOVA_PROVEEDOR MODIFY PROV_PROVEEDOR DROP IDENTITY;
ALTER TABLE NOVA_COMPRA MODIFY COMP_COMPRA DROP IDENTITY;
ALTER TABLE NOVA_DETALLE_COMPRA MODIFY DETCOM_DETALLE_COMPRA DROP IDENTITY;
ALTER TABLE NOVA_CLIENTE MODIFY CLI_CLIENTE DROP IDENTITY;
ALTER TABLE NOVA_PEDIDO MODIFY PED_PEDIDO DROP IDENTITY;
ALTER TABLE NOVA_DETALLE_PEDIDO MODIFY DETPED_DETALLE_PEDIDO DROP IDENTITY;
ALTER TABLE NOVA_VENTA MODIFY VENT_VENTA DROP IDENTITY;
ALTER TABLE NOVA_DETALLE_VENTA MODIFY DETVEN_DETALLE_VENTA DROP IDENTITY;
ALTER TABLE NOVA_PAGO MODIFY PAG_PAGO DROP IDENTITY;
ALTER TABLE NOVA_AUDITORIA MODIFY AUDI_AUDITORIA DROP IDENTITY;

-- ------------------------------------------------------------
-- PASO 2: crear una secuencia por tabla
-- ------------------------------------------------------------
CREATE SEQUENCE SEQ_ROL START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_USU START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MAR START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRODU START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VAR START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ALM START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INV START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MOVI START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PROV START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COMP START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DETCOM START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CLI START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PED START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DETPED START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VENT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DETVEN START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PAG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AUDI START WITH 1 INCREMENT BY 1 NOCACHE;

-- ------------------------------------------------------------
-- PASO 3: un trigger BEFORE INSERT por tabla, que asigna el
-- siguiente valor de la secuencia solo si no se mandó un ID
-- ------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_ROL_BI
BEFORE INSERT ON NOVA_ROL
FOR EACH ROW
WHEN (NEW.ROL_ROL IS NULL)
BEGIN
    :NEW.ROL_ROL := SEQ_ROL.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_USU_BI
BEFORE INSERT ON NOVA_USUARIO
FOR EACH ROW
WHEN (NEW.USU_USUARIO IS NULL)
BEGIN
    :NEW.USU_USUARIO := SEQ_USU.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_MAR_BI
BEFORE INSERT ON NOVA_MARCA
FOR EACH ROW
WHEN (NEW.MAR_MARCA IS NULL)
BEGIN
    :NEW.MAR_MARCA := SEQ_MAR.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_CATE_BI
BEFORE INSERT ON NOVA_CATEGORIA
FOR EACH ROW
WHEN (NEW.CATE_CATEGORIA IS NULL)
BEGIN
    :NEW.CATE_CATEGORIA := SEQ_CATE.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_PRODU_BI
BEFORE INSERT ON NOVA_PRODUCTO
FOR EACH ROW
WHEN (NEW.PRODU_PRODUCTO IS NULL)
BEGIN
    :NEW.PRODU_PRODUCTO := SEQ_PRODU.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_VAR_BI
BEFORE INSERT ON NOVA_VARIANTE
FOR EACH ROW
WHEN (NEW.VAR_VARIANTE IS NULL)
BEGIN
    :NEW.VAR_VARIANTE := SEQ_VAR.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_ALM_BI
BEFORE INSERT ON NOVA_ALMACEN
FOR EACH ROW
WHEN (NEW.ALM_ALMACEN IS NULL)
BEGIN
    :NEW.ALM_ALMACEN := SEQ_ALM.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_INV_BI
BEFORE INSERT ON NOVA_INVENTARIO
FOR EACH ROW
WHEN (NEW.INV_INVENTARIO IS NULL)
BEGIN
    :NEW.INV_INVENTARIO := SEQ_INV.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_MOVI_BI
BEFORE INSERT ON NOVA_MOVIMIENTO_INVENTARIO
FOR EACH ROW
WHEN (NEW.MOVI_MOVIMIENTO IS NULL)
BEGIN
    :NEW.MOVI_MOVIMIENTO := SEQ_MOVI.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_PROV_BI
BEFORE INSERT ON NOVA_PROVEEDOR
FOR EACH ROW
WHEN (NEW.PROV_PROVEEDOR IS NULL)
BEGIN
    :NEW.PROV_PROVEEDOR := SEQ_PROV.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_COMP_BI
BEFORE INSERT ON NOVA_COMPRA
FOR EACH ROW
WHEN (NEW.COMP_COMPRA IS NULL)
BEGIN
    :NEW.COMP_COMPRA := SEQ_COMP.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_DETCOM_BI
BEFORE INSERT ON NOVA_DETALLE_COMPRA
FOR EACH ROW
WHEN (NEW.DETCOM_DETALLE_COMPRA IS NULL)
BEGIN
    :NEW.DETCOM_DETALLE_COMPRA := SEQ_DETCOM.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_CLI_BI
BEFORE INSERT ON NOVA_CLIENTE
FOR EACH ROW
WHEN (NEW.CLI_CLIENTE IS NULL)
BEGIN
    :NEW.CLI_CLIENTE := SEQ_CLI.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_PED_BI
BEFORE INSERT ON NOVA_PEDIDO
FOR EACH ROW
WHEN (NEW.PED_PEDIDO IS NULL)
BEGIN
    :NEW.PED_PEDIDO := SEQ_PED.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_DETPED_BI
BEFORE INSERT ON NOVA_DETALLE_PEDIDO
FOR EACH ROW
WHEN (NEW.DETPED_DETALLE_PEDIDO IS NULL)
BEGIN
    :NEW.DETPED_DETALLE_PEDIDO := SEQ_DETPED.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_VENT_BI
BEFORE INSERT ON NOVA_VENTA
FOR EACH ROW
WHEN (NEW.VENT_VENTA IS NULL)
BEGIN
    :NEW.VENT_VENTA := SEQ_VENT.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_DETVEN_BI
BEFORE INSERT ON NOVA_DETALLE_VENTA
FOR EACH ROW
WHEN (NEW.DETVEN_DETALLE_VENTA IS NULL)
BEGIN
    :NEW.DETVEN_DETALLE_VENTA := SEQ_DETVEN.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_PAG_BI
BEFORE INSERT ON NOVA_PAGO
FOR EACH ROW
WHEN (NEW.PAG_PAGO IS NULL)
BEGIN
    :NEW.PAG_PAGO := SEQ_PAG.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDI_BI
BEFORE INSERT ON NOVA_AUDITORIA
FOR EACH ROW
WHEN (NEW.AUDI_AUDITORIA IS NULL)
BEGIN
    :NEW.AUDI_AUDITORIA := SEQ_AUDI.NEXTVAL;
END;
/
