-- ============================================================
-- NOVA — SISTEMA DE COMPRAS, INVENTARIO, PEDIDOS Y VENTAS
-- Tienda de ropa (hombre/mujer, varias marcas)
-- ORACLE DATABASE 12c+
-- Convención: NOVA_<TABLA> / <ABREVIATURA>_<ATRIBUTO>
-- ============================================================

-- ------------------------------------------------------------
-- NOVA_ROL
-- ------------------------------------------------------------
CREATE TABLE NOVA_ROL (
    ROL_ROL         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROL_NOMBRE      VARCHAR2(50) NOT NULL UNIQUE,
    ROL_DESCRIPCION VARCHAR2(150),
    ROL_PERMISO     VARCHAR2(100),
    ROL_ACTIVO      NUMBER(1) DEFAULT 1 NOT NULL CHECK (ROL_ACTIVO IN (0,1))
);

-- ------------------------------------------------------------
-- NOVA_USUARIO
-- ------------------------------------------------------------
CREATE TABLE NOVA_USUARIO (
    USU_USUARIO    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROL_ROL        NUMBER NOT NULL REFERENCES NOVA_ROL(ROL_ROL),
    USU_NOMBRE     VARCHAR2(100) NOT NULL,
    USU_EMAIL      VARCHAR2(120) NOT NULL UNIQUE,
    USU_PASSWORD   VARCHAR2(255) NOT NULL,  -- almacenar siempre con hash (bcrypt)
    USU_ACTIVO     NUMBER(1) DEFAULT 1 NOT NULL CHECK (USU_ACTIVO IN (0,1)),
    USU_CREADO     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ------------------------------------------------------------
-- NOVA_MARCA
-- ------------------------------------------------------------
CREATE TABLE NOVA_MARCA (
    MAR_MARCA       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MAR_NOMBRE      VARCHAR2(80) NOT NULL UNIQUE,   -- Nike, Adidas, Zara, Distefano...
    MAR_DESCRIPCION VARCHAR2(200),
    MAR_ACTIVO NUMBER(1) DEFAULT 1 NOT NULL CHECK (MAR_ACTIVO IN (0,1))
);

-- ------------------------------------------------------------
-- NOVA_CATEGORIA
-- ------------------------------------------------------------
CREATE TABLE NOVA_CATEGORIA (
    CATE_CATEGORIA   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CATE_NOMBRE      VARCHAR2(80) NOT NULL,   -- Camisas, Pantalones, Zapatos, Vestidos...
    CATE_DESCRIPCION VARCHAR2(200)
);

-- ------------------------------------------------------------
-- NOVA_PRODUCTO (producto genérico; el detalle vendible vive en NOVA_VARIANTE)
-- ------------------------------------------------------------
CREATE TABLE NOVA_PRODUCTO (
    PRODU_PRODUCTO    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CATE_CATEGORIA    NUMBER NOT NULL REFERENCES NOVA_CATEGORIA(CATE_CATEGORIA),
    MAR_MARCA         NUMBER NOT NULL REFERENCES NOVA_MARCA(MAR_MARCA),
    PRODU_NOMBRE      VARCHAR2(150) NOT NULL,
    PRODU_DESCRIPCION CLOB,
    PRODU_GENERO      VARCHAR2(10) NOT NULL CHECK (PRODU_GENERO IN ('HOMBRE','MUJER','UNISEX')),
    PRODU_TEMPORADA   VARCHAR2(30),
    PRODU_ACTIVO      NUMBER(1) DEFAULT 1 NOT NULL CHECK (PRODU_ACTIVO IN (0,1)),
    PRODU_CREADO      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ------------------------------------------------------------
-- NOVA_VARIANTE (talla / color — lo que realmente se compra, vende y almacena)
-- ------------------------------------------------------------
CREATE TABLE NOVA_VARIANTE (
    VAR_VARIANTE       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRODU_PRODUCTO     NUMBER NOT NULL REFERENCES NOVA_PRODUCTO(PRODU_PRODUCTO) ON DELETE CASCADE,
    VAR_TALLA          VARCHAR2(10) NOT NULL,
    VAR_COLOR          VARCHAR2(30) NOT NULL,
    VAR_SKU            VARCHAR2(50) NOT NULL UNIQUE,
    VAR_PRECIO_COMPRA  NUMBER(12,2) DEFAULT 0 NOT NULL,
    VAR_PRECIO_VENTA   NUMBER(12,2) DEFAULT 0 NOT NULL,
    VAR_STOCK_MINIMO   NUMBER DEFAULT 0 NOT NULL,
    VAR_ACTIVO         NUMBER(1) DEFAULT 1 NOT NULL CHECK (VAR_ACTIVO IN (0,1)),
    CONSTRAINT UQ_VARIANTE UNIQUE (PRODU_PRODUCTO, VAR_TALLA, VAR_COLOR)
);

-- ------------------------------------------------------------
-- NOVA_ALMACEN
-- ------------------------------------------------------------
CREATE TABLE NOVA_ALMACEN (
    ALM_ALMACEN   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ALM_NOMBRE    VARCHAR2(80) NOT NULL,
    ALM_UBICACION VARCHAR2(150)
);

-- ------------------------------------------------------------
-- NOVA_INVENTARIO (stock consolidado por variante/almacén)
-- ------------------------------------------------------------
CREATE TABLE NOVA_INVENTARIO (
    INV_INVENTARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VAR_VARIANTE   NUMBER NOT NULL REFERENCES NOVA_VARIANTE(VAR_VARIANTE),
    ALM_ALMACEN    NUMBER NOT NULL REFERENCES NOVA_ALMACEN(ALM_ALMACEN),
    INV_CANTIDAD   NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT UQ_INVENTARIO UNIQUE (VAR_VARIANTE, ALM_ALMACEN)
);

-- ------------------------------------------------------------
-- NOVA_MOVIMIENTO_INVENTARIO (kardex: auditoría de todo movimiento)
-- ------------------------------------------------------------
CREATE TABLE NOVA_MOVIMIENTO_INVENTARIO (
    MOVI_MOVIMIENTO      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VAR_VARIANTE         NUMBER NOT NULL REFERENCES NOVA_VARIANTE(VAR_VARIANTE),
    ALM_ALMACEN          NUMBER NOT NULL REFERENCES NOVA_ALMACEN(ALM_ALMACEN),
    MOVI_TIPO            VARCHAR2(10) NOT NULL CHECK (MOVI_TIPO IN ('ENTRADA','SALIDA')),
    MOVI_CANTIDAD        NUMBER NOT NULL CHECK (MOVI_CANTIDAD > 0),
    MOVI_TIPO_DOCUMENTO  VARCHAR2(20) NOT NULL,  -- 'COMPRA', 'VENTA', 'AJUSTE'
    MOVI_DOCUMENTO_ID    NUMBER,
    USU_USUARIO          NUMBER NOT NULL REFERENCES NOVA_USUARIO(USU_USUARIO),
    MOVI_FECHA           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    MOVI_OBSERVACION     VARCHAR2(200)
);

-- ------------------------------------------------------------
-- NOVA_PROVEEDOR
-- ------------------------------------------------------------
CREATE TABLE NOVA_PROVEEDOR (
    PROV_PROVEEDOR NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROV_NOMBRE    VARCHAR2(120) NOT NULL,
    PROV_RUC_NIT   VARCHAR2(30),
    PROV_TELEFONO  VARCHAR2(30),
    PROV_CORREO    VARCHAR2(120),
    PROV_DIRECCION VARCHAR2(200)
);

-- ------------------------------------------------------------
-- NOVA_COMPRA
-- ------------------------------------------------------------
CREATE TABLE NOVA_COMPRA (
    COMP_COMPRA    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROV_PROVEEDOR NUMBER NOT NULL REFERENCES NOVA_PROVEEDOR(PROV_PROVEEDOR),
    USU_USUARIO    NUMBER NOT NULL REFERENCES NOVA_USUARIO(USU_USUARIO),
    COMP_FECHA     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    COMP_ESTADO    VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL
                   CHECK (COMP_ESTADO IN ('PENDIENTE','RECIBIDA','CANCELADA')),
    COMP_TOTAL     NUMBER(12,2) DEFAULT 0 NOT NULL
);

-- ------------------------------------------------------------
-- NOVA_DETALLE_COMPRA
-- ------------------------------------------------------------
CREATE TABLE NOVA_DETALLE_COMPRA (
    DETCOM_DETALLE_COMPRA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COMP_COMPRA           NUMBER NOT NULL REFERENCES NOVA_COMPRA(COMP_COMPRA) ON DELETE CASCADE,
    VAR_VARIANTE          NUMBER NOT NULL REFERENCES NOVA_VARIANTE(VAR_VARIANTE),
    DETCOM_CANTIDAD        NUMBER NOT NULL CHECK (DETCOM_CANTIDAD > 0),
    DETCOM_PRECIO_UNITARIO NUMBER(12,2) NOT NULL,
    DETCOM_SUBTOTAL        NUMBER(12,2) NOT NULL
);

-- ------------------------------------------------------------
-- NOVA_CLIENTE
-- ------------------------------------------------------------
CREATE TABLE NOVA_CLIENTE (
    CLI_CLIENTE   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLI_NOMBRE    VARCHAR2(120) NOT NULL,
    CLI_DPI_NIT   VARCHAR2(30),
    CLI_TELEFONO  VARCHAR2(30),
    CLI_CORREO    VARCHAR2(120),
    CLI_DIRECCION VARCHAR2(200)
);

-- ------------------------------------------------------------
-- NOVA_PEDIDO
-- ------------------------------------------------------------
CREATE TABLE NOVA_PEDIDO (
    PED_PEDIDO  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLI_CLIENTE NUMBER NOT NULL REFERENCES NOVA_CLIENTE(CLI_CLIENTE),
    USU_USUARIO NUMBER NOT NULL REFERENCES NOVA_USUARIO(USU_USUARIO),
    PED_FECHA   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    PED_ESTADO  VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL
                CHECK (PED_ESTADO IN ('PENDIENTE','FACTURADO','CANCELADO')),
    PED_TOTAL   NUMBER(12,2) DEFAULT 0 NOT NULL
);

-- ------------------------------------------------------------
-- NOVA_DETALLE_PEDIDO
-- ------------------------------------------------------------
CREATE TABLE NOVA_DETALLE_PEDIDO (
    DETPED_DETALLE_PEDIDO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PED_PEDIDO            NUMBER NOT NULL REFERENCES NOVA_PEDIDO(PED_PEDIDO) ON DELETE CASCADE,
    VAR_VARIANTE          NUMBER NOT NULL REFERENCES NOVA_VARIANTE(VAR_VARIANTE),
    DETPED_CANTIDAD        NUMBER NOT NULL CHECK (DETPED_CANTIDAD > 0),
    DETPED_PRECIO_UNITARIO NUMBER(12,2) NOT NULL,
    DETPED_SUBTOTAL        NUMBER(12,2) NOT NULL
);

-- ------------------------------------------------------------
-- NOVA_VENTA
-- ------------------------------------------------------------
CREATE TABLE NOVA_VENTA (
    VENT_VENTA  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PED_PEDIDO  NUMBER REFERENCES NOVA_PEDIDO(PED_PEDIDO),   -- opcional: venta directa sin pedido previo
    CLI_CLIENTE NUMBER NOT NULL REFERENCES NOVA_CLIENTE(CLI_CLIENTE),
    USU_USUARIO NUMBER NOT NULL REFERENCES NOVA_USUARIO(USU_USUARIO),
    VENT_FECHA  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    VENT_ESTADO VARCHAR2(20) DEFAULT 'COMPLETADA' NOT NULL
                CHECK (VENT_ESTADO IN ('COMPLETADA','ANULADA')),
    VENT_TOTAL  NUMBER(12,2) DEFAULT 0 NOT NULL
);

-- ------------------------------------------------------------
-- NOVA_DETALLE_VENTA
-- ------------------------------------------------------------
CREATE TABLE NOVA_DETALLE_VENTA (
    DETVEN_DETALLE_VENTA   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VENT_VENTA             NUMBER NOT NULL REFERENCES NOVA_VENTA(VENT_VENTA) ON DELETE CASCADE,
    VAR_VARIANTE           NUMBER NOT NULL REFERENCES NOVA_VARIANTE(VAR_VARIANTE),
    DETVEN_CANTIDAD        NUMBER NOT NULL CHECK (DETVEN_CANTIDAD > 0),
    DETVEN_PRECIO_UNITARIO NUMBER(12,2) NOT NULL,
    DETVEN_SUBTOTAL        NUMBER(12,2) NOT NULL
);

-- ------------------------------------------------------------
-- NOVA_PAGO
-- ------------------------------------------------------------
CREATE TABLE NOVA_PAGO (
    PAG_PAGO   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VENT_VENTA NUMBER NOT NULL REFERENCES NOVA_VENTA(VENT_VENTA),
    PAG_FECHA  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    PAG_MONTO  NUMBER(12,2) NOT NULL,
    PAG_METODO VARCHAR2(30) NOT NULL CHECK (PAG_METODO IN ('EFECTIVO','TARJETA','TRANSFERENCIA'))
);

-- ------------------------------------------------------------
-- NOVA_AUDITORIA (bitácora general de cambios, siguiendo el patrón del diagrama)
-- ------------------------------------------------------------
CREATE TABLE NOVA_AUDITORIA (
    AUDI_AUDITORIA      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AUDI_TABLA          VARCHAR2(50) NOT NULL,     -- nombre de la tabla afectada
    AUDI_ACCION         VARCHAR2(10) NOT NULL CHECK (AUDI_ACCION IN ('INSERT','UPDATE','DELETE')),
    AUDI_CAMPO          VARCHAR2(50),
    AUDI_VALOR_ANTES    VARCHAR2(4000),
    AUDI_VALOR_DESPUES  VARCHAR2(4000),
    USU_USUARIO         NUMBER REFERENCES NOVA_USUARIO(USU_USUARIO),
    AUDI_FECHA          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ------------------------------------------------------------
-- ÍNDICES RECOMENDADOS
-- ------------------------------------------------------------
CREATE INDEX IDX_PRODU_CATE ON NOVA_PRODUCTO(CATE_CATEGORIA);
CREATE INDEX IDX_PRODU_MAR  ON NOVA_PRODUCTO(MAR_MARCA);
CREATE INDEX IDX_PRODU_GENERO ON NOVA_PRODUCTO(PRODU_GENERO);
CREATE INDEX IDX_VAR_PRODU  ON NOVA_VARIANTE(PRODU_PRODUCTO);
CREATE INDEX IDX_MOVI_VAR   ON NOVA_MOVIMIENTO_INVENTARIO(VAR_VARIANTE, ALM_ALMACEN);
CREATE INDEX IDX_COMP_PROV  ON NOVA_COMPRA(PROV_PROVEEDOR);
CREATE INDEX IDX_VENT_CLI   ON NOVA_VENTA(CLI_CLIENTE);
CREATE INDEX IDX_PED_CLI    ON NOVA_PEDIDO(CLI_CLIENTE);


-- ------------------------------------------------------------
-- TRIGGER: actualizar NOVA_INVENTARIO al registrar un movimiento
-- ------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_MOVI_INVENTARIO
AFTER INSERT ON NOVA_MOVIMIENTO_INVENTARIO
FOR EACH ROW
DECLARE
    v_delta NUMBER;
BEGIN
    v_delta := CASE WHEN :NEW.MOVI_TIPO = 'ENTRADA'
                     THEN :NEW.MOVI_CANTIDAD
                     ELSE -:NEW.MOVI_CANTIDAD
               END;

    MERGE INTO NOVA_INVENTARIO inv
    USING (SELECT :NEW.VAR_VARIANTE AS VAR_VARIANTE, :NEW.ALM_ALMACEN AS ALM_ALMACEN FROM dual) src
    ON (inv.VAR_VARIANTE = src.VAR_VARIANTE AND inv.ALM_ALMACEN = src.ALM_ALMACEN)
    WHEN MATCHED THEN
        UPDATE SET inv.INV_CANTIDAD = inv.INV_CANTIDAD + v_delta
    WHEN NOT MATCHED THEN
        INSERT (VAR_VARIANTE, ALM_ALMACEN, INV_CANTIDAD)
        VALUES (src.VAR_VARIANTE, src.ALM_ALMACEN, v_delta);
END;
/





